---

- name: Download helm
  unarchive:
    src: "{{ helm_url }}"
    dest: /tmp
    copy: no
  tags: download

- name: Create the installation directory
  file:
    path: "{{ helm_bin_dir }}"
    state: directory

- name: Copy helm binary
  copy:
    src: /tmp/linux-amd64/helm
    dest: "{{ helm_bin_dir }}"
    mode: 0755
    remote_src: yes